import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  cardStyle,
  headerStyle,
  movingCardStyle,
  responsiveHeading,
} from "../ve-styles/style.css";
import Accordion from "../components/accordion";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={headerStyle.header}>
          <p>フレックスボックス</p>
          <p>ボックス</p>
          <p>ボックス</p>
          <p>ボックス</p>
        </div>
        <div style={{ margin: "100px 0" }}>
          <div className={`${movingCardStyle} ${headerStyle.header}`}>
            アニメーションカード
          </div>
        </div>
        <div>
          <p>:hoverの書き方</p>
          <div className={cardStyle.simpleCard}>シンプルカード</div>
          <div className={cardStyle.simpleCard}>シンプルカード</div>
        </div>
        <div>
          <p className={responsiveHeading}>VEにおけるclamp</p>
        </div>

        <div>
          <h1>アコーディオンのサンプル</h1>
          <Accordion title="Accordion 1">
            <p>コンテンツ</p>
            <p>コンテンツ</p>
            <p>コンテンツ</p>
            <p>コンテンツ</p>
          </Accordion>
          <Accordion title="Accordion 2">
            <ol>
              <li>リスト</li>
              <li>リスト</li>
              <li>リスト</li>
              <li>リスト</li>
            </ol>
          </Accordion>
          <Accordion title="Accordion 3">
            <ol>
              <li>リスト</li>
              <li>リスト</li>
              <li>リスト</li>
              <li>リスト</li>
            </ol>
          </Accordion>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
